/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/api/users/me': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 프로필 조회
         * @description 현재 로그인한 유저의 프로필 정보를 조회합니다.
         */
        get: operations['getUserProfile'];
        /**
         * 마이페이지 프로필 수정
         * @description 닉네임, MBTI, 어필 항목, 연락처를 수정합니다. 온보딩 완료 유저만 수정 가능합니다.
         */
        put: operations['updateUserProfile'];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/webhook/bank': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations['receive'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/users/onboarding': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 온보딩 프로필 등록
         * @description 닉네임, MBTI, 성별, 연락처, 어필 문구를 등록하고 온보딩을 완료합니다. 온보딩은 1회만 가능합니다.
         */
        post: operations['registerUserOnboarding'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/users/nickname/validate': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 닉네임 검증
         * @description 닉네임의 길이, 비속어 포함 여부, 중복 여부를 검증합니다. 최대 10자까지 사용할 수 있습니다.
         */
        post: operations['validateNickname'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/payments/{paymentId}/verify': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 결제 검증 및 쿠폰 충전
         * @description PortOne 결제 단건 조회 결과를 기반으로 결제 상태와 금액을 검증하고 쿠폰을 충전합니다.
         *
         *     - 이미 처리된 결제(paymentId 중복)이면 기존 결제 결과를 그대로 반환합니다.
         *     - 결제 상태가 PAID가 아니거나 금액이 상품 가격과 다르면 실패합니다.
         */
        post: operations['verifyPayment'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/payments/checkout': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 결제 HTML 생성
         * @description READY 결제 기록을 생성하고 PortOne Browser SDK로 결제창을 여는 테스트용 HTML을 반환합니다.
         */
        post: operations['getCheckoutPage'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/oauth/kakao/login': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 카카오 소셜 로그인
         * @description 프론트엔드에서 전달받은 카카오 인가 코드(code)와 리다이렉트 타입(LOCAL/PROD)으로 로그인 또는 회원가입을 처리하고 서비스 JWT를 발급합니다.
         */
        post: operations['kakaoLogin'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/auth/token/reissue': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 토큰 재발급
         * @description Authorization 헤더에 'Bearer {refreshToken}' 형식으로 전달하면 액세스 토큰과 리프레시 토큰을 재발급합니다.
         */
        post: operations['reissue'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/auth/test/login': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 테스트 로그인
         * @description testUserId로 유저를 조회하거나 없으면 자동 생성 후 JWT를 발급합니다. secretKey로 접근을 제한합니다.
         */
        post: operations['login'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/auth/logout': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그아웃
         * @description 리프레시 토큰을 무효화하여 로그아웃 처리합니다.
         */
        post: operations['logout'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/ai-images': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * AI 이미지 목록 조회
         * @description 현재 유저가 생성한 AI 이미지 전체 목록을 최신순으로 반환합니다. 각 이미지는 7일 만료 Presigned URL로 제공됩니다.
         */
        get: operations['getImageList'];
        put?: never;
        /**
         * AI 이미지 생성
         * @description 사용자의 원본 사진을 업로드하면 동물의 숲 스타일 3D 캐릭터 이미지를 생성합니다.
         *     - 1인당 최대 3회 생성 가능 (서버에서 관리)
         *     - 프론트에서 1024px로 리사이징 후 전송 권장
         *     - 지원 형식: JPEG, PNG (최대 10MB)
         */
        post: operations['generateImage'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/admin/login': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 관리자 로그인
         * @description 관리자 전용 계정으로 로그인하고 관리자 API 접근용 access token을 발급합니다.
         */
        post: operations['login_1'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/admin/deposit-events/{eventId}/assign': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 관리자 입금 이벤트 수동 매칭
         * @description 관리자가 입금 이벤트를 유저와 수동 매칭하고 쿠폰을 충전합니다.
         */
        post: operations['assignDepositEvent'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/admin/coupons/add': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 관리자 쿠폰 수동 충전
         * @description 관리자가 선택한 유저 ID와 쿠폰 상품으로 쿠폰을 수동 충전하고 감사 로그를 남깁니다.
         */
        post: operations['addCoupon'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/users/me/phone-number': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 결제용 전화번호 등록/수정
         * @description 쿠폰 결제에 사용할 전화번호를 하이픈 없이 등록하거나 수정합니다.
         */
        patch: operations['updatePhoneNumber'];
        trace?: never;
    };
    '/api/ai-images/{aiImageId}/select': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 최종 프로필 이미지 확정
         * @description 생성된 이미지 중 하나를 최종 프로필 이미지로 선택합니다.
         *     - 기존에 선택된 이미지가 있으면 자동으로 해제됩니다.
         *     - 선택된 이미지는 프로필 카드의 대표 이미지로 반영됩니다.
         */
        patch: operations['selectProfileImage'];
        trace?: never;
    };
    '/api/users': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 유저 카드 리스트 조회
         * @description 온보딩을 완료한 유저 목록을 카드 형태로 조회합니다.
         *
         *     - 인증된 요청: 본인을 제외한 목록을 반환합니다.
         *     - 비인증 요청: 전체 목록을 반환합니다. (토큰 없이 호출 가능)
         */
        get: operations['getUserCardList'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/users/{targetUserId}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 상대 유저 프로필 조회
         * @description 특정 유저의 프로필을 조회합니다.
         *
         *     - 첫 열람 시 쿠폰 1개를 차감합니다.
         *     - 재열람 시 쿠폰을 차감하지 않고 열람 시간만 갱신합니다.
         *     - 탈퇴 유저 및 온보딩 미완료 유저는 조회 불가합니다.
         *     - 본인 프로필은 조회 불가합니다.
         */
        get: operations['getTargetUserProfile'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/users/me/profile-views': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 열람 목록 통합 조회
         * @description 내가 열람한 유저 목록과 나를 열람한 유저 목록을 한 번에 조회합니다. 각각 최신순으로 반환됩니다.
         */
        get: operations['getProfileViewList'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/payments/coupon-products': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 쿠폰 상품 목록 조회
         * @description 프론트 결제 화면에 표시할 쿠폰 상품 코드, 가격, 지급 수량을 조회합니다.
         */
        get: operations['getCouponProducts'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/ai-images/{aiImageId}/status': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * AI 이미지 단건 상태 조회
         * @description 생성 요청 후 PENDING 상태인 이미지의 완료 여부를 폴링할 때 사용합니다.
         *     - 프론트에서 3~5초 간격으로 반복 호출 권장
         *     - status: PENDING(생성 중) / DONE(완료) / FAILED(실패)
         *     - DONE 상태일 때 generatedImageUrl이 채워집니다.
         */
        get: operations['getImageStatus'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/admin/users': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 관리자 유저 검색
         * @description userId, 이름, 닉네임, 이메일, 전화번호로 유저를 검색합니다.
         */
        get: operations['searchUsers'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/admin/deposit-events': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 관리자 입금 이벤트 목록 조회
         * @description 자동 처리되지 않았거나 검토가 필요한 입금 이벤트 목록을 조회합니다.
         */
        get: operations['getDepositEvents'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/auth/withdraw': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 회원 탈퇴
         * @description 회원을 탈퇴 처리합니다. soft delete 방식으로 처리되며 동일 소셜 계정으로 재가입이 가능합니다.
         */
        delete: operations['withdraw'];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/checkpay.jsp': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations['check'];
        put: operations['check_2'];
        post: operations['check_1'];
        delete: operations['check_3'];
        options: operations['check_6'];
        head: operations['check_5'];
        patch: operations['check_4'];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 마이페이지 프로필 수정 요청 */
        UpdateUserProfileRequest: {
            /**
             * @description 닉네임
             * @example 숭실대 카리나
             */
            nickname?: string;
            /**
             * @description MBTI
             * @example INTJ
             */
            mbti?: string;
            /**
             * @description 어필 항목 (최대 3개)
             * @example [
             *       "고양이상",
             *       "키 160cm",
             *       "청순"
             *     ]
             */
            appeals: string[];
            /**
             * @description 연락처 (인스타그램, 전화번호 등)
             * @example @ssu_pick
             */
            contact?: string;
        };
        ApiResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: Record<string, never>;
        };
        ApiResponseVoid: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: Record<string, never>;
        };
        BankDepositWebhookRequest: {
            eventKey?: string;
            depositorName?: string;
            /** Format: int64 */
            amount: number;
            /** Format: date-time */
            depositedAt?: string;
            rawText?: string;
        };
        ApiResponseBankDepositWebhookResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            data?: components['schemas']['BankDepositWebhookResponse'];
        };
        BankDepositWebhookResponse: {
            /** Format: int64 */
            eventId?: number;
            status?: string;
            duplicated?: boolean;
        };
        /** @description 유저 온보딩 프로필 등록 요청 */
        RegisterUserOnboardingRequest: {
            /**
             * @description 닉네임
             * @example 숭실대 카리나
             */
            nickname?: string;
            /**
             * @description MBTI
             * @example INTJ
             */
            mbti?: string;
            /**
             * @description 상대방에게 어필할 항목 (최대 3개)
             * @example [
             *       "고양이상",
             *       "160cm",
             *       "청순"
             *     ]
             */
            appeals: string[];
            /**
             * @description 연락처 (인스타그램, 전화번호 등)
             * @example @ssu_pick
             */
            contact?: string;
            /**
             * @description 성별 (여자, 남자)
             * @example MALE OR FEMALE
             * @enum {string}
             */
            gender: 'MALE' | 'FEMALE';
        };
        /** @description 닉네임 검증 요청 */
        ValidateNicknameRequest: {
            /**
             * @description 검증할 닉네임
             * @example 숭실대 카리나
             */
            nickname?: string;
        };
        /** @description 닉네임 검증 응답 */
        ValidateNicknameResponse: {
            /**
             * @description 닉네임 사용 가능 여부
             * @example true
             */
            available?: boolean;
        };
        PaymentVerifyRequest: {
            /** @enum {string} */
            couponProduct: 'COUPON_1' | 'COUPON_4' | 'COUPON_8';
        };
        PaymentVerifyResponse: {
            paymentId?: string;
            status?: string;
            /** Format: int64 */
            totalAmount?: number;
            /** Format: int32 */
            chargedCouponCount?: number;
            /** Format: int32 */
            remainingCouponCount?: number;
        };
        OAuthKakaoLoginRequest: {
            code?: string;
            /** @enum {string} */
            deviceType: 'IOS' | 'ANDROID';
            /** @enum {string} */
            redirectType: 'LOCAL' | 'PROD';
        };
        OAuthLoginResponse: {
            /** Format: int64 */
            userId?: number;
            accessToken?: string;
            refreshToken?: string;
            onboardingCompleted?: boolean;
            aiImageGenerated?: boolean;
            randomNickname?: string;
            firstLogin?: boolean;
        };
        ReissueResponse: {
            accessToken?: string;
            refreshToken?: string;
        };
        LoginRequest: {
            testUserId?: string;
            /** @enum {string} */
            deviceType: 'IOS' | 'ANDROID';
        };
        LoginResponse: {
            /** Format: int64 */
            userId?: number;
            accessToken?: string;
            refreshToken?: string;
            onboardingCompleted?: boolean;
            aiImageGenerated?: boolean;
            /** Format: int32 */
            remainingCouponCount?: number;
            randomNickname?: string;
            firstLogin?: boolean;
        };
        AiImageResponse: {
            /** Format: int64 */
            aiImageId?: number;
            /** @enum {string} */
            status?: 'PENDING' | 'DONE' | 'FAILED';
            originalImageUrl?: string;
            generatedImageUrl?: string;
            selected?: boolean;
            /** Format: int32 */
            remainingCount?: number;
            /** Format: int32 */
            totalCount?: number;
        };
        AdminLoginRequest: {
            username?: string;
            password?: string;
        };
        AdminLoginResponse: {
            accessToken?: string;
        };
        BankDepositAssignRequest: {
            /** Format: int64 */
            userId: number;
            /** @enum {string} */
            couponProduct?: 'COUPON_1' | 'COUPON_4' | 'COUPON_8';
        };
        BankDepositEventResponse: {
            /** Format: int64 */
            eventId?: number;
            eventKey?: string;
            bankName?: string;
            depositorName?: string;
            /** Format: int64 */
            amount?: number;
            /** Format: date-time */
            depositedAt?: string;
            couponProduct?: string;
            /** Format: int64 */
            matchedUserId?: number;
            matchedUserName?: string;
            matchedUserNickname?: string;
            status?: string;
            /** Format: date-time */
            processedAt?: string;
        };
        AdminCouponAddRequest: {
            /** Format: int64 */
            userId: number;
            /** @enum {string} */
            couponProduct: 'COUPON_1' | 'COUPON_4' | 'COUPON_8';
        };
        AdminCouponAddResponse: {
            /** Format: int64 */
            adjustmentId?: number;
            /** Format: int64 */
            userId?: number;
            /** Format: int32 */
            chargedCouponCount?: number;
            /** Format: int32 */
            remainingCouponCount?: number;
        };
        /** @description 전화번호 등록/수정 요청 */
        UpdatePhoneNumberRequest: {
            /**
             * @description 결제에 사용할 전화번호
             * @example 01012345678
             */
            phoneNumber?: string;
        };
        /** @description 유저 카드 응답 (리스트 조회용) */
        GetUserCardResponse: {
            /**
             * Format: int64
             * @description 유저 ID
             * @example 1
             */
            userId?: number;
            /**
             * @description 닉네임
             * @example 숭실대 카리나
             */
            nickname?: string;
            /**
             * @description 유저 성별
             * @example MALE OR FEMALE
             * @enum {string}
             */
            gender?: 'MALE' | 'FEMALE';
            /**
             * @description MBTI
             * @example INTJ
             */
            mbti?: string;
            /**
             * @description 어필 항목 목록
             * @example [
             *       "고양이상",
             *       "160cm",
             *       "청순"
             *     ]
             */
            appeals?: string[];
            /**
             * @description 프로필 이미지 URL
             * @example https://example.com/profile.jpg
             */
            profileUrl?: string;
        };
        /** @description 상대 유저 프로필 조회 응답 */
        GetTargetUserProfileResponse: {
            /**
             * Format: int64
             * @description 유저 ID
             * @example 2
             */
            userId?: number;
            /**
             * @description 닉네임
             * @example 숭실대 차은우
             */
            nickname?: string;
            /**
             * @description MBTI
             * @example INTJ
             */
            mbti?: string;
            /**
             * @description 프로필 이미지 URL
             * @example https://example.com/profile.jpg
             */
            profileUrl?: string;
            /**
             * @description 어필 항목 목록
             * @example [
             *       "고양이상",
             *       "160cm",
             *       "청순"
             *     ]
             */
            appeals?: string[];
            /**
             * @description 연락처 (잠금 해제 후 노출)
             * @example @ssu_pick
             */
            contact?: string;
        };
        /** @description 유저 프로필 조회 응답 */
        GetUserProfileResponse: {
            /**
             * Format: int64
             * @description 유저 ID
             * @example 1
             */
            userId?: number;
            /**
             * @description 이름
             * @example 홍길동
             */
            name?: string;
            /**
             * @description 이메일
             * @example hong@example.com
             */
            email?: string;
            /**
             * @description 프로필 이미지 URL
             * @example https://example.com/profile.jpg
             */
            profileUrl?: string;
            /**
             * @description 성별
             * @example MALE
             * @enum {string}
             */
            gender?: 'MALE' | 'FEMALE';
            /**
             * Format: int32
             * @description 나이
             * @example 25
             */
            age?: number;
            /**
             * @description 온보딩 상태
             * @example COMPLETED
             * @enum {string}
             */
            onboardingStatus?: 'INCOMPLETE' | 'COMPLETED';
            /**
             * @description 닉네임
             * @example 숭실대 카리나
             */
            nickname?: string;
            /**
             * @description MBTI
             * @example INTJ
             */
            mbti?: string;
            /**
             * @description 연락처
             * @example @ssu_pick
             */
            contact?: string;
            /**
             * @description 결제용 전화번호
             * @example 01012345678
             */
            phoneNumber?: string;
            /**
             * @description 어필 항목 목록
             * @example [
             *       "고양이상",
             *       "160cm",
             *       "청순"
             *     ]
             */
            appeals?: string[];
            /**
             * Format: int32
             * @description 남은 쿠폰 갯수
             * @example 1
             */
            remainingCouponCount?: number;
        };
        /** @description 열람 목록 통합 응답 */
        GetProfileViewListResponse: {
            /** @description 내가 열람한 유저 목록 */
            viewedUsers?: components['schemas']['GetUserViewResponse'][];
            /** @description 나를 열람한 유저 목록 */
            viewerUsers?: components['schemas']['GetUserViewResponse'][];
        };
        /** @description 열람 유저 응답 (내가 열람한 / 나를 열람한 리스트용) */
        GetUserViewResponse: {
            /**
             * Format: int64
             * @description 유저 ID
             * @example 2
             */
            userId?: number;
            /**
             * @description 닉네임
             * @example 숭실대 차은우
             */
            nickname?: string;
            /**
             * @description 성별
             * @example MALE
             * @enum {string}
             */
            gender?: 'MALE' | 'FEMALE';
            /**
             * @description MBTI
             * @example ESFP
             */
            mbti?: string;
            /**
             * @description 어필 항목 목록
             * @example [
             *       "최대8글자입니다"
             *     ]
             */
            appeals?: string[];
            /**
             * @description 프로필 이미지 URL
             * @example https://example.com/profile.jpg
             */
            profileUrl?: string;
            /**
             * Format: date-time
             * @description 열람 시각
             * @example 2025-05-07T14:30:00
             */
            viewedAt?: string;
        };
        CouponProductResponse: {
            productCode?: string;
            orderName?: string;
            /** Format: int32 */
            couponCount?: number;
            /** Format: int64 */
            price?: number;
        };
        AdminUserSearchResponse: {
            /** Format: int64 */
            userId?: number;
            name?: string;
            nickname?: string;
            email?: string;
            phoneNumber?: string;
            oauthProvider?: string;
            onboardingStatus?: string;
            /** Format: int32 */
            remainingCouponCount?: number;
        };
        RtPayCheckResponse: {
            RCODE?: string;
            PCHK?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getUserProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 프로필 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['GetUserProfileResponse'];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
            /** @description 유저를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
        };
    };
    updateUserProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['UpdateUserProfileRequest'];
            };
        };
        responses: {
            /** @description 프로필 수정 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponseVoid'];
                };
            };
            /** @description 잘못된 요청 (유효성 검사 실패) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
            /** @description 온보딩 미완료 유저 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
            /** @description 유저를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
        };
    };
    receive: {
        parameters: {
            query?: never;
            header: {
                'Bank-Webhook-Secret': string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['BankDepositWebhookRequest'];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponseBankDepositWebhookResponse'];
                };
            };
        };
    };
    registerUserOnboarding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['RegisterUserOnboardingRequest'];
            };
        };
        responses: {
            /** @description 프로필 등록 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponseVoid'];
                };
            };
            /** @description 잘못된 요청 (유효성 검사 실패 또는 어필 항목 오류) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
            /** @description 유저를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
            /** @description 이미 온보딩 완료 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
        };
    };
    validateNickname: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['ValidateNicknameRequest'];
            };
        };
        responses: {
            /** @description 사용 가능한 닉네임 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ValidateNicknameResponse'];
                };
            };
            /** @description 잘못된 요청 또는 비속어 포함 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
            /** @description 이미 사용 중인 닉네임 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
        };
    };
    verifyPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description PortOne 결제 고유 ID */
                paymentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['PaymentVerifyRequest'];
            };
        };
        responses: {
            /** @description 결제 검증 및 쿠폰 충전 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['PaymentVerifyResponse'];
                };
            };
            /** @description 잘못된 요청, 결제 상태 불일치 또는 금액 불일치 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
            /** @description 유저를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
            /** @description 이미 처리된 결제 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
        };
    };
    getCheckoutPage: {
        parameters: {
            query: {
                /** @description 쿠폰 상품 코드 (COUPON_1 / COUPON_4 / COUPON_8) */
                couponProduct: 'COUPON_1' | 'COUPON_4' | 'COUPON_8';
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description HTML 반환 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'text/html': string;
                };
            };
            /** @description 잘못된 쿠폰 상품 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'text/html': components['schemas']['ApiResponse'];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'text/html': components['schemas']['ApiResponse'];
                };
            };
            /** @description 유저를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'text/html': components['schemas']['ApiResponse'];
                };
            };
        };
    };
    kakaoLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['OAuthKakaoLoginRequest'];
            };
        };
        responses: {
            /** @description 로그인 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['OAuthLoginResponse'];
                };
            };
            /** @description 잘못된 요청 (인가 코드, 디바이스 타입 또는 리다이렉트 타입 누락) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
            /** @description 카카오 API 호출 실패 */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
        };
    };
    reissue: {
        parameters: {
            query?: never;
            header: {
                /** @description 리프레시 토큰 */
                'Refresh-Token': string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 토큰 재발급 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ReissueResponse'];
                };
            };
            /** @description 리프레시 토큰 만료 또는 불일치 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header: {
                /** @description 테스트 시크릿 키 */
                'Test-Secret-Key': string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['LoginRequest'];
            };
        };
        responses: {
            /** @description 로그인 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['LoginResponse'];
                };
            };
            /** @description 잘못된 요청 (testUserId, deviceType, secretKey 누락) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
            /** @description 시크릿 키 불일치 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 로그아웃 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponseVoid'];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
        };
    };
    getImageList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 목록 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['AiImageResponse'];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
        };
    };
    generateImage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                'multipart/form-data': {
                    /** Format: binary */
                    originalImage: string;
                };
            };
        };
        responses: {
            /** @description 이미지 생성 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['AiImageResponse'];
                };
            };
            /** @description 잘못된 파일 형식 또는 크기 초과 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
            /** @description 이미지 생성 횟수 초과 */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
            /** @description Gemini API 호출 실패 */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
        };
    };
    login_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['AdminLoginRequest'];
            };
        };
        responses: {
            /** @description 관리자 로그인 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['AdminLoginResponse'];
                };
            };
            /** @description 잘못된 요청 (username, password 누락) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
            /** @description 관리자 인증 실패 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
        };
    };
    assignDepositEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 입금 이벤트 ID */
                eventId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['BankDepositAssignRequest'];
            };
        };
        responses: {
            /** @description 입금 이벤트 수동 매칭 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['BankDepositEventResponse'];
                };
            };
            /** @description 입금 이벤트 또는 유저 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
        };
    };
    addCoupon: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['AdminCouponAddRequest'];
            };
        };
        responses: {
            /** @description 관리자 쿠폰 충전 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['AdminCouponAddResponse'];
                };
            };
            /** @description 유저 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
        };
    };
    updatePhoneNumber: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['UpdatePhoneNumberRequest'];
            };
        };
        responses: {
            /** @description 전화번호 등록 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponseVoid'];
                };
            };
            /** @description 잘못된 요청 (유효성 검사 실패) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
            /** @description 유저를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
        };
    };
    selectProfileImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                aiImageId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 프로필 이미지 확정 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponseVoid'];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
            /** @description 본인 이미지가 아님 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
            /** @description 이미지를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
        };
    };
    getUserCardList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 리스트 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['GetUserCardResponse'];
                };
            };
        };
    };
    getTargetUserProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 조회할 상대 유저 ID */
                targetUserId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 상대 프로필 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['GetTargetUserProfileResponse'];
                };
            };
            /** @description 본인 프로필 조회 불가 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
            /** @description 쿠폰 부족 */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
            /** @description 온보딩 미완료 유저 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
            /** @description 유저를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
        };
    };
    getProfileViewList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['GetProfileViewListResponse'];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
            /** @description 유저를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
        };
    };
    getCouponProducts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 상품 목록 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['CouponProductResponse'];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
        };
    };
    getImageStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                aiImageId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 상태 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['AiImageResponse'];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
            /** @description 본인 이미지가 아님 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
            /** @description 이미지를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
        };
    };
    searchUsers: {
        parameters: {
            query?: {
                /** @description 검색어 */
                keyword?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 관리자 유저 검색 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['AdminUserSearchResponse'];
                };
            };
        };
    };
    getDepositEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 입금 이벤트 목록 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['BankDepositEventResponse'];
                };
            };
        };
    };
    withdraw: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 회원 탈퇴 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponseVoid'];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['ApiResponse'];
                };
            };
        };
    };
    check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['RtPayCheckResponse'];
                };
            };
        };
    };
    check_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['RtPayCheckResponse'];
                };
            };
        };
    };
    check_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['RtPayCheckResponse'];
                };
            };
        };
    };
    check_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['RtPayCheckResponse'];
                };
            };
        };
    };
    check_6: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['RtPayCheckResponse'];
                };
            };
        };
    };
    check_5: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['RtPayCheckResponse'];
                };
            };
        };
    };
    check_4: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    '*/*': components['schemas']['RtPayCheckResponse'];
                };
            };
        };
    };
}
